name: Docker Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t cplusfull .

    - name: Tag Docker image
      run: docker tag cplusfull ${{ secrets.DOCKER_USERNAME }}/cplusfull:1

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cplusfull:1
